# Security Sandbox Configuration for Rhiza Agent
# Enforces strict security boundaries for research agents

sandbox_profiles:
  # Builder agent profile - higher resources for analysis
  builder:
    resource_limits:
      memory: "512MB"
      cpu: "1.0"
      disk: "1GB"
      network_bandwidth: "10Mbps"
      max_execution_time: 300  # 5 minutes
      
    filesystem:
      allowed_paths:
        read:
          - "/data/agents/rhiza_agent/adapters"
          - "/data/research_artifacts"
          - "/tmp/rhiza_builder_*"
        write:
          - "/tmp/rhiza_builder_*"
          - "/data/research_artifacts/pending"
      denied_paths:
        - "/etc"
        - "/usr"
        - "/data/agents/*/credentials"
        
    network:
      allowed_domains:
        - "arxiv.org"
        - "export.arxiv.org"
        - "localhost:8080"  # NocoDB
      blocked_ports:
        - 22  # SSH
        - 3389  # RDP
      rate_limits:
        requests_per_minute: 60
        
    process:
      allowed_executables:
        - "python3"
        - "node"
        - "curl"
      forbidden_syscalls:
        - "fork"
        - "exec"
        - "ptrace"
        
    environment:
      allowed_env_vars:
        - "TRACE_ID"
        - "AGENT_ID"
        - "NOCODB_API_URL"
      scrubbed_env_vars:
        - "*_KEY"
        - "*_TOKEN"
        - "*_SECRET"

  # Validator agent profile - restricted for security
  validator:
    resource_limits:
      memory: "256MB"
      cpu: "0.5"
      disk: "500MB"
      network_bandwidth: "5Mbps"
      max_execution_time: 120  # 2 minutes
      
    filesystem:
      allowed_paths:
        read:
          - "/data/research_artifacts"
          - "/data/schemas"
          - "/tmp/rhiza_validator_*"
        write:
          - "/tmp/rhiza_validator_*"
          - "/data/validation_reports"
      denied_paths:
        - "/data/agents/*/adapters"  # Cannot access builder code
        
    network:
      allowed_domains:
        - "localhost:8080"  # NocoDB only
      blocked_ports: "*"  # No external network
      
    process:
      allowed_executables:
        - "python3"
      forbidden_syscalls:
        - "fork"
        - "exec"
        - "socket"
        
    environment:
      allowed_env_vars:
        - "TRACE_ID"
        - "AGENT_ID"
      scrubbed_env_vars: "*"  # Minimal environment

# Security policies
security_policies:
  input_validation:
    max_input_size: "10MB"
    allowed_content_types:
      - "application/json"
      - "text/plain"
    sanitization_rules:
      - strip_html_tags
      - escape_special_chars
      - validate_json_structure
      
  output_validation:
    max_output_size: "50MB"
    required_fields:
      - "artifact_id"
      - "evidence_chain"
      - "signature"
    forbidden_content:
      - "private_key"
      - "password"
      - "secret"
      
  evidence_requirements:
    min_evidence_steps: 3
    require_timestamps: true
    require_hashes: true
    hash_algorithm: "SHA-256"
    
  audit_logging:
    log_level: "INFO"
    log_format: "structured_json"
    required_fields:
      - "trace_id"
      - "agent_id"
      - "action"
      - "timestamp"
    retention_days: 90
    
# Runtime monitoring
monitoring:
  metrics:
    - name: "agent_execution_time"
      type: "histogram"
      labels: ["agent_type", "action"]
      
    - name: "validation_failures"
      type: "counter"
      labels: ["failure_type", "agent_id"]
      
    - name: "resource_usage"
      type: "gauge"
      labels: ["resource_type", "agent_id"]
      
  alerts:
    - name: "execution_timeout"
      condition: "execution_time > max_execution_time"
      severity: "warning"
      action: "terminate_and_log"
      
    - name: "memory_exceeded"
      condition: "memory_usage > memory_limit"
      severity: "critical"
      action: "terminate_immediately"
      
    - name: "suspicious_network"
      condition: "network_request to blocked_domain"
      severity: "critical"
      action: "block_and_alert"
      
    - name: "validation_anomaly"
      condition: "validation_failure_rate > 0.3"
      severity: "warning"
      action: "notify_operator"

# Enforcement mechanisms
enforcement:
  container_runtime: "docker"
  security_modules:
    - "apparmor"
    - "seccomp"
    
  namespace_isolation:
    enabled: true
    network_policy: "deny_all_except_allowed"
    
  capabilities_drop:
    - "CAP_SYS_ADMIN"
    - "CAP_NET_ADMIN"
    - "CAP_SYS_PTRACE"
    
  readonly_rootfs: true
  no_new_privileges: true

# Recovery procedures
recovery:
  on_sandbox_breach:
    - action: "terminate_agent"
    - action: "quarantine_artifacts"
    - action: "alert_security_team"
    - action: "initiate_forensics"
    
  on_validation_failure:
    - action: "mark_artifact_invalid"
    - action: "trigger_revalidation"
    - action: "log_detailed_report"
    
  on_resource_exhaustion:
    - action: "graceful_shutdown"
    - action: "save_partial_results"
    - action: "queue_for_retry"