# generated: 2026-02-24
# Session 439: WORK-164 Agent Cards
"""Generate AGENTS.md from agent capability card frontmatter.

Produces a vendor-neutral, auto-generated markdown file listing all agents
with their capabilities, contracts, and invocation patterns.

Usage:
    python .claude/haios/lib/generate_agents_md.py

Output:
    AGENTS.md at project root (anchored via Path(__file__), not cwd).
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure agent_cards is importable (critique A2)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from agent_cards import list_agents


# Project root anchored to script location (critique A9)
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent


def generate_agents_md() -> str:
    """Generate AGENTS.md content from agent frontmatter.

    Returns:
        Markdown string ready to write to AGENTS.md.
    """
    agents = list_agents()
    agents_sorted = sorted(agents, key=lambda a: a.name)

    lines: list[str] = []

    # Header
    lines.append("<!-- AUTO-GENERATED by generate_agents_md.py — DO NOT EDIT MANUALLY -->")
    lines.append("<!-- Regenerate with: just agents -->")
    lines.append("")
    lines.append("# AGENTS")
    lines.append("")
    lines.append(f"**{len(agents_sorted)} agents** available in the HAIOS system.")
    lines.append("")
    lines.append("This file is the vendor-neutral discovery layer for agent capabilities.")
    lines.append("Source of truth: `.claude/agents/*.md` frontmatter.")
    lines.append("")

    # Summary table
    lines.append("## Agent Registry")
    lines.append("")
    lines.append("| Agent | Model | Requirement | Category | Purpose |")
    lines.append("|-------|-------|-------------|----------|---------|")
    for agent in agents_sorted:
        desc = agent.description.split(".")[0] if agent.description else ""
        lines.append(
            f"| **{agent.name}** | {agent.model} | {agent.requirement_level} "
            f"| {agent.category} | {desc} |"
        )
    lines.append("")

    # Per-category sections
    categories = {}
    for agent in agents_sorted:
        cat = agent.category
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(agent)

    category_order = ["gate", "verification", "utility", "cycle-delegation"]
    category_labels = {
        "gate": "Required Gates",
        "verification": "Verification Agents",
        "utility": "Utility Agents",
        "cycle-delegation": "Cycle Delegation Agents",
    }

    for cat in category_order:
        if cat not in categories:
            continue
        label = category_labels.get(cat, cat)
        lines.append(f"### {label}")
        lines.append("")
        for agent in categories[cat]:
            lines.append(f"**{agent.name}** ({agent.model})")
            lines.append(f"- Requirement: {agent.requirement_level}")
            if agent.trigger_conditions:
                triggers = ", ".join(agent.trigger_conditions)
                lines.append(f"- Triggers: {triggers}")
            if agent.input_contract:
                lines.append(f"- Input: {agent.input_contract}")
            if agent.output_contract:
                lines.append(f"- Output: {agent.output_contract}")
            if agent.produces:
                lines.append(f"- Produces: {', '.join(agent.produces)}")
            if agent.consumes:
                lines.append(f"- Consumes: {', '.join(agent.consumes)}")
            if agent.capabilities:
                lines.append(f"- Capabilities: {', '.join(agent.capabilities)}")
            lines.append("")

    # Invocation pattern
    lines.append("## Invocation Pattern")
    lines.append("")
    lines.append("```python")
    lines.append("Task(subagent_type='<agent-name>', prompt='<task description>')")
    lines.append("```")
    lines.append("")

    # Data flow
    lines.append("## Data Flow")
    lines.append("")
    lines.append("| Agent | Produces | Consumes |")
    lines.append("|-------|----------|----------|")
    for agent in agents_sorted:
        produces = ", ".join(agent.produces) if agent.produces else "-"
        consumes = ", ".join(agent.consumes) if agent.consumes else "-"
        lines.append(f"| {agent.name} | {produces} | {consumes} |")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Source: `.claude/agents/*.md` frontmatter (REQ-DISCOVER-003, REQ-DISCOVER-004)*")
    lines.append("")

    return "\n".join(lines)


def write_agents_md() -> Path:
    """Generate and write AGENTS.md to project root.

    Returns:
        Path to the written file.
    """
    content = generate_agents_md()
    output_path = _PROJECT_ROOT / "AGENTS.md"
    output_path.write_text(content, encoding="utf-8")
    return output_path


if __name__ == "__main__":
    path = write_agents_md()
    print(f"Generated: {path}")
