services:
  n8n:
    image: n8nio/n8n:1.100.1
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - localnet
    env_file: .env

  nocodb:
    image: nocodb/nocodb:0.263.8
    ports:
      - "${NOCODB_PORT}:8080"
    volumes:
      - ./data/nocodb:/usr/app/data
    networks:
      - localnet
    env_file: .env

  langflow:
    image: langflowai/langflow:1.4.3
    ports:
      - "${LANGFLOW_PORT}:7860"
    env_file: .env
    volumes:
      - ./data/langflow:/data/langflow
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
