services:
  n8n:
    image: n8nio/n8n:1.100.1
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - localnet
    env_file: .env

  nocodb:
    image: nocodb/nocodb:0.263.8
    ports:
      - "${NOCODB_PORT}:8080"
    volumes:
      - ./data/nocodb:/usr/app/data
    networks:
      - localnet
    env_file: .env

  langflow:
    image: langflowai/langflow:1.4.3
    ports:
      - "${LANGFLOW_PORT}:7860"
    env_file: .env
    volumes:
      - ./data/langflow:/data/langflow
    networks:
      - localnet

  # Claude-as-a-Service for Rhiza agent
  claude-server:
    build:
      context: ./agents/rhiza_agent
      dockerfile: claude-server/Dockerfile
    command: ["claude", "mcp", "serve", "--port", "8090"]
    volumes:
      - .:/app/project:ro  # Read-only mount of entire project for CLAUDE.md
    working_dir: /app/project
    networks:
      - localnet
    env_file: .env
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - rhiza-v3  # Use docker compose --profile rhiza-v3 up

networks:
  localnet:
    driver: bridge
